from pathlib import Path

root_path = Path(__file__).parent

bet15_img_path = root_path / "Grafika" / "Obiekty" / "bet1,5p.png"
bet1_img_path = root_path / "Grafika" / "Obiekty" / "bet1p.png"
bet05_img_path = root_path / "Grafika" / "Obiekty" / "bet0.5.png"
hit_img_path = root_path / "Grafika" / "Obiekty" / "hit.png"
stand_img_path = root_path / "Grafika" / "Obiekty" / "STAND.png"
double_img_path = root_path / "Grafika" / "Obiekty" / "double.png"
card_back_img_path = root_path / "Grafika" / "Karty" / "tyl_karty.png"
leave_img_path = root_path / "Grafika" / "Obiekty" / "leave.png"
StartScreenPath = root_path / 'Grafika' / 'Tla' / 'StartScreen_background.png'
name_text_path = root_path / "Grafika" / "Czcionki" / "Aptos.ttf"
points_text_path = root_path / "Grafika" / "Czcionki" / "Aptos.ttf"
Dante_background_path = root_path / "Grafika" / "Tla" / "danteekran.png"
StartScreen_background_path = root_path / "Grafika" / "Tla" / "dante_start_screen_background.png"
dante_task_background_path = root_path / "Grafika" / "Tla" / "ekranzadan.png"
task_background_path = root_path / "Grafika" / "Tla" / "ekrandozadania.png"
Game_background_path = root_path / "Grafika" / "Tla" / "table.png"
font_0_path = root_path / "Grafika" / "Czcionki" / "Aptos.ttf"
Lobby_background_path = root_path / "Grafika" / "Tla" / "background_lobby.png"
text_lobby_blackspace_path = root_path / "Grafika" / "Czcionki" / "Aptos.ttf"
lobby_players1_path = root_path / "Grafika" / "Obiekty" / "lobby_players1.png"
lobby_players2_path = root_path / "Grafika" / "Obiekty" / "lobby_players2.png"
lobby_players3_path = root_path / "Grafika" / "Obiekty" / "lobby_players3.png"
lobby_players4_path = root_path / "Grafika" / "Obiekty" / "lobby_players4.png"
login_background_path = root_path / "Grafika" / "Tla" / "Ekran_Logowania.png"
music_path = root_path / "muzyka" / "music.mp3"
Rules_background_path = root_path / "Grafika" / "Tla" / "Rules_background.png"
task_1_path = root_path / "Grafika" / "Obiekty" / "zad11.png"
task_2_path = root_path / "Grafika" / "Obiekty" / "zad12.png"
task_3_path = root_path / "Grafika" / "Obiekty" / "zad13.png"
task_4_path = root_path / "Grafika" / "Obiekty" / "zad14.png"
task_5_path = root_path / "Grafika" / "Obiekty" / "zad15.png"

